HomeLibrary/Controllers/CommunityController.cs
using HomeLibrary.DAL;
using HomeLibrary.Models;
using HomeLibrary.Services.Community;
using HomeLibrary.Services.ManageServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HomeLibrary.Controllers
{
    public class CommunityController : Controller
    {
        // GET: Community
        public ActionResult Messages()
        {
            return View();
        }
        public async Task<dynamic> Users(string searchValue)
        {
            FriendsServices fs = new FriendsServices();
            var model = await fs.FindUser(searchValue);
            ViewData["searchV"] = searchValue;
            //var model = db.Friends.ToList();

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Users(FormCollection collection)
        {
            FriendsServices fs = new FriendsServices();
            bool succes = await fs.IvitationManager(collection[0]);            

            return RedirectToAction("Users", new { searchValue = collection[1] });
        }
        public ActionResult AccountSettings()
        {
            return View();
        }
        public async Task<ActionResult> InformationManager()
        {
            InformationManagerServices ims = new InformationManagerServices();
            var model = await ims.SelectProfileInfoAsync();

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> InformationManager(FormCollection collection, BasicProfileInfoModels bpi)
        {

            InformationManagerServices ims = new InformationManagerServices();
            var model = await ims.SelectProfileInfoAsync();
            if (ModelState.IsValid && User.Identity.IsAuthenticated)
            {
                var t = await ims.ProfileUpdateManager(collection[2], collection[1]);

                return RedirectToAction("InformationManager"); 
            }
            else
            {
                return View(model);
            }

        }
        public async Task<ActionResult> UserProfile()
        {
            ProfileServices ps = new ProfileServices();
            var model = await ps.SelectProfile();

            return View(model);
        }
        public async Task<ActionResult> PicturesProfile()
        {
            ProfileServices ps = new ProfileServices();
            var model = await ps.PhotosManager();

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> PicturesProfile(HttpPostedFileBase file, string choseToRemove)
        {
            if (file != null && file.ContentLength > 0)
            {
                ProfileServices ps = new ProfileServices();
                bool result = await ps.PicturesManagerAsync(file);
            }
            else if (choseToRemove.Length > 0)
            {
                //ToDo...
                ProfileServices ps = new ProfileServices();
                await ps.RemovePcituresAsync(choseToRemove);
            }

            return RedirectToAction("PicturesProfile");
        }
        [HttpPost]
        public async Task<ActionResult> PicturesSetter(FormCollection collection)
        {
            ProfileServices ps = new ProfileServices();
            int t = -1;
            int c = -1;
            if (collection[0] != "")
            {
                 t = Convert.ToInt32(collection[0]);
            }
            else if (collection[1] != "")
            {
                 c = Convert.ToInt32(collection[1]);
            }
            

            bool result = await ps.SetPicture(t, c);

            return RedirectToAction("PicturesProfile");
        }
        public async Task<ActionResult> Friends()
        {
            FriendsServices fs = new FriendsServices();
            var model = await fs.CreateFriendListAsync();
            ViewData["notification"] = await fs.OverallNotificationAsync(); 

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> InvitationAccept(FormCollection collection)
        {
            HomeLibraryConnection db = new HomeLibraryConnection();
            FriendsServices fs = new FriendsServices();
            bool success = await fs.AddFriendManager(collection[0]);
            //var model = db.Friends.ToList();

            return RedirectToAction("Friends");
        }
        public async Task<ActionResult> Invitations(int notiAmount = 0)
        {
            FriendsServices fs = new FriendsServices();
            var model = await fs.CreateInvitationsAsync(notiAmount);

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Invitations(string invID)
        {
            FriendsServices fs = new FriendsServices();
            bool result = await fs.InvitationCloser(invID);
            //var model = await fs.CreateInvitationsAsync();

            return RedirectToAction("Invitations");
        }
        [HttpPost]
        public async Task<ActionResult> FriendsProfile(string fID)
        {
            FriendsServices fs = new FriendsServices();
            var model = await fs.FriendsProfileManager(Convert.ToInt32(fID));

            return View(model);
        }
        public async Task<ActionResult> FriendsPictures(int profileID)
        {
            FriendsServices fs = new FriendsServices();
            var model = await fs.friendPhotoManager(profileID);

            return View(model);
        }
        public async Task<ActionResult> FriendsInformations(int profileID)
        {
            FriendsServices fs = new FriendsServices();
            var model = await fs.FriendsProfileManager(profileID);

            return View(model);
        }
        public async Task<ActionResult> FriendsUserList(int profileID)
        {
            FriendsServices fs = new FriendsServices();
            var model = await fs.GetListFriendsAsync(profileID);

            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> FriendUserList(string pId, int thisProfileId)
        {
            FriendsServices fs = new FriendsServices();
            bool result = await fs.IvitationManager(pId);

            return RedirectToAction("FriendsUserList", new { profileID = thisProfileId });
        }
    }
}

HomeLibrary/Views/Community/Friends.cshtml
@model List<HomeLibrary.Models.Friends>
@{
    int amount = ViewBag.notification;
}
<div id="users-view" class="users-view-content">
    @using (Html.BeginForm("FriendsProfile", "Community", FormMethod.Post, new { id = "fProfileForm", enctype = "multipart/form-data" }))
    {
        <input type="hidden" name="fID" />
    }
    <div id="users-search" class="users-list">
        <div class="friend-list-header">
            <div class="space-button"></div>
            <div id="friends-btn" class="friends-button">
                Friends
            </div>
            <div class="space-button"></div>
            @if (amount != 0)
            {
                <div id="invs-btn" class="invitations-button-noti" value=@amount>
                    <p>Invitations</p>
                    <div class="noti-strike">
                        @if (amount < 10)
                        {
                            <p>@amount</p>
                        }
                        else
                        {
                            <p>9+</p>
                        }
                    </div>
                </div>
            }
            else
            {
                <div id="invs-btn" class="invitations-button">
                    <p>Invitations</p>
                </div>
            }
            <div class="space-button"></div>
        </div>
        @using (Html.BeginForm("InvitationAccept", "Community", FormMethod.Post, new { id = "userForm" }))
        {
            foreach (var f in Model)
            {
                if (f != null)
                {
                    <div class="user" value=@f.Profile.ProfileID>
                        <div class="user-picture" style="background-image: url('@Url.Content("~/Images/" + f.Profile.ProfilePic)" )')"></div>
                        <div class="user-info">
                            <div class="nameSector">
                                <label class="user-info-name">@f.Profile.Nickname</label>
                            </div>
                            <div class="citySector">
                                <label class="user-info-loc">@f.Profile.City</label>
                            </div>
                        </div>
                        <div class="add-friend-btn-container">
                            <div class="remove-friend-btn">- Remove</div>
                        </div>
                    </div>
                }
            }
            <input type="hidden" name="pId" />
        }
    </div>
</div>

HomeLibrary/Views/Community/FriendsUserList.cshtml
@using HomeLibrary
@model dynamic
<div id="profile-view" class="profile-view-content">
    <div id="profile-head" class="head-profile" style="background-image: url('@Url.Content("~/Images/" + Model.Profile.BackgroundPic)" )')" value=@Model.Profile.BackgroundPic>
        <div id="profile-mask" class="profile-head-mask"></div>
        <div id="profile-photo" class="photo-profile" style="background-image: url('@Url.Content("~/Images/" + Model.Profile.ProfilePic)" )')" value=@Model.Profile.ProfilePic>
        </div>
        <label class="nickname-profile">@Model.Profile.Nickname</label>
    </div>
    <div class="head-profile-bottom">
        <ul class="profile-navbar">
            <li class="profile-navbar-li"><a href="/Community/FriendsPictures?profileID=@Model.Profile.ProfileID">Photos</a></li>
            <li class="profile-navbar-li"><a href="/Community/FriendsInformations?profileID=@Model.Profile.ProfileID">Informations</a></li>
            <li class="profile-navbar-li"><a href="/Community/FriendsUserList?profileID=@Model.Profile.ProfileID">Friends</a></li>
        </ul>
    </div>
    <div id="profile-body" class="corpse-profile">
        @using (Html.BeginForm("FriendsProfile", "Community", FormMethod.Post, new { id = "fProfileForm", enctype = "multipart/form-data" }))
        {
            <input type="hidden" name="fID" />
        }
        <div id="users-search" class="users-list">
            <div class="user-list-header">Users</div>
            @using (Html.BeginForm("FriendUserList", "Community", FormMethod.Post, new { id = "inviteForm" }))
            {
                if (Model.userList != null && Model.userList.Count > 0)
                {
                    for (int i = 0; i < Model.userList.Count; i++)
                    {
                        if (Model.friendList[i])
                        {
                            <div class="user" value=@Model.userList[i].ProfileID>
                                <div class="user-picture" style="background-image: url('@Url.Content("~/Images/" + Model.userList[i].ProfilePic)" )')"></div>
                                <div class="user-info">
                                    <div class="nameSector">
                                        <label class="user-info-name">@Model.userList[i].Nickname</label>
                                    </div>
                                    <div class="citySector">
                                        <label class="user-info-loc">@Model.userList[i].City</label>
                                    </div>
                                </div>
                                <div class="add-friend-btn-container">
                                    <div class="removeFriend">- Remove</div>
                                </div>
                            </div>
                        }
                        else if (Model.invitedList[i])
                        {
                            <div class="user" value=@Model.userList[i].ProfileID>
                                <div class="user-picture" style="background-image: url('@Url.Content("~/Images/" + Model.userList[i].ProfilePic)" )')"></div>
                                <div class="user-info">
                                    <div class="nameSector">
                                        <label class="user-info-name">@Model.userList[i].Nickname</label>
                                    </div>
                                    <div class="citySector">
                                        <label class="user-info-loc">@Model.userList[i].City</label>
                                    </div>
                                </div>
                                <div class="add-friend-btn-container">
                                    <div class="repeatInv">Invited</div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="user" value=@Model.userList[i].ProfileID>
                                <div class="user-picture" style="background-image: url('@Url.Content("~/Images/" + Model.userList[i].ProfilePic)" )')"></div>
                                <div class="user-info">
                                    <div class="nameSector">
                                        <label class="user-info-name">@Model.userList[i].Nickname</label>
                                    </div>
                                    <div class="citySector">
                                        <label class="user-info-loc">@Model.userList[i].City</label>
                                    </div>
                                </div>
                                <div class="add-friend-btn-container">
                                    <div class="invFriend">+ Add</div>
                                </div>
                            </div>
                        }
                    }
                }
                else
                {
                    <div class="user">
                        No search result
                    </div>
                }
                <input type="hidden" name="pId" />
                <input type="hidden" name="thisProfileId" value=@Model.Profile.ProfileID />
            }
        </div>
    </div>
</div>

HomeLibrary/Views/Community/InformationManager.cshtml
@model HomeLibrary.Models.BasicProfileInfoModels

<div id="SinglePageContent" class="body-content-blank">
    <div class="library-view-content">
        <div id="right-panel" class="right-panel-section">
            <div class="library-navbar">
                <div class="library-navbar-header">
                    <p>Category</p>
                    <img id="close-navbar" src="~/Images/leave_btn.png" />
                </div>
                <ul class="library-navbar-list">
                    <li>
                        <img src="@Url.Content("~/Images/menu_arrow.png")" />
                        <a href="/Community/InformationManager">Change profile informations</a>
                    </li>
                    <li>
                        <img src="@Url.Content("~/Images/menu_arrow.png")" />
                        <a href="/Library/BorrowedBooks">Change account informations</a>
                    </li>
                    <li>
                        <img src="@Url.Content("~/Images/menu_arrow.png")" />
                        <a href="/Library/LendBooks">Block users</a>
                    </li>
                    <li>
                        <img src="@Url.Content("~/Images/menu_arrow.png")" />
                        <a href="/Community/PicturesProfile">Manage pictures</a>
                    </li>
                </ul>
            </div>
        </div>
        <div id="navbar-open" class="close-navbar-button">
            Open
        </div>
        <div id="left-panel" class="left-panel-section">
            @using (Html.BeginForm("InformationManager", "Community", FormMethod.Post, new { id = "editProfile", enctype = "multipart/form-data" }))
            {
                <div class="left-panel-content">
                    <div class="header-add-book">Change profile informations</div>
                    <div class="right-panel-manage">
                        <div class="right-panel-content-manage">
                            <ul id="profile-info-list" class="profile-info">
                                @Html.AntiForgeryToken()
                                <li id="Nickname-li">
                                    <div class="left-panel-left-label profile-field-name">
                                        @Html.Label("Nickname")
                                    </div>
                                    @if (Model.Nickname == null)
                                    {
                                        <div class="left-panel-book-field profile-field-value">
                                            <p class="profile-info-field">unknown</p>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="left-panel-book-field profile-field-value">
                                            <p class="profile-info-field">@Model.Nickname</p>
                                        </div>
                                    }
                                    <div name="Nickname-btn" id="Nickname-btn" class="left-panel-book-field profile-info-btn" value="@Model.Nickname">
                                        Edit
                                    </div>
                                </li>
                                <li id="Age-li">
                                    <div class="left-panel-left-label profile-field-name">
                                        @Html.Label("Age")
                                    </div>
                                    @if (Model.Age == 0)
                                    {
                                        <div class="left-panel-book-field profile-field-value">
                                            <p class="profile-info-field">unknown</p>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="left-panel-book-field profile-field-value">
                                            <p class="profile-info-field">@Model.Age</p>
                                        </div>
                                    }
                                    <div id="Age-btn" class="left-panel-book-field profile-info-btn" value="@Model.Age">
                                        Edit
                                    </div>
                                </li>
                                <li id="Country-li">
                                    <div class="left-panel-left-label profile-field-name">
                                        @Html.Label("Country")
                                    </div>
                                    <div class="left-panel-book-field profile-field-value">
                                        <p class="profile-info-field">@Model.Country</p>
                                    </div>
                                    <div id="Country-btn" class="left-panel-book-field profile-info-btn" value="@Model.Country">
                                        Edit
                                    </div>
                                </li>
                                <li id="City-li">
                                    <div class="left-panel-left-label profile-field-name">
                                        @Html.Label("City")
                                    </div>
                                    <div class="left-panel-book-field profile-field-value">
                                        <p class="profile-info-field">@Model.City</p>
                                    </div>
                                    <div id="City-btn" class="left-panel-book-field profile-info-btn" value="@Model.City">
                                        Edit
                                    </div>
                                </li>
                                <li id="Quote-li">
                                    <div class="left-panel-left-label profile-field-name">
                                        @Html.Label("Favourite quote")
                                    </div>
                                    <div class="left-panel-book-field profile-field-value">
                                        <p class="profile-info-field">@Model.Quote</p>
                                    </div>
                                    <div id="Quote-btn" class="left-panel-book-field profile-info-btn" value="@Model.Quote">
                                        Edit
                                    </div>
                                </li>
                                <li id="Category-li">
                                    <div class="left-panel-left-label profile-field-name">
                                        @Html.Label("Favourite book category")
                                    </div>
                                    <div class="left-panel-book-field profile-field-value">
                                        <p class="profile-info-field">@Model.FavouriteBookCategory</p>
                                    </div>
                                    <div id="Category-btn" class="left-panel-book-field profile-info-btn" value="@Model.FavouriteBookCategory">
                                        Edit
                                    </div>
                                </li>
                                <li id="Book-li" class="last-li">
                                    <div class="left-panel-left-label profile-field-name">
                                        @Html.Label("Favourite book")
                                    </div>
                                    <div class="left-panel-book-field profile-field-value">
                                        <p class="profile-info-field">@Model.FavouriteBook</p>
                                    </div>
                                    <div id="Book-btn" class="left-panel-book-field profile-info-btn" value="@Model.FavouriteBook">
                                        Edit
                                    </div>
                                </li>
                            </ul>
                            <div class="error">
                                @Html.ValidationSummary(false, "", new { @class = "error" })
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

HomeLibrary/Views/Community/Invitations.cshtml
@model List<HomeLibrary.Models.Invitations>

<div id="users-view" class="users-view-content">
    @using (Html.BeginForm("Friends", "Community", FormMethod.Post, new { id = "Search-form", enctype = "multipart/form-data" }))
    {

    }
    <div id="users-search" class="users-list">
        <div class="friend-list-header">
            <div class="space-button"></div>
            <div id="friends-btn" class="friends-button">
                Friends
            </div>
            <div class="space-button"></div>
            <div id="invs-btn" class="invitations-button">
                Invitations
            </div>
            <div class="space-button"></div>
        </div>
        @using (Html.BeginForm("Invitations", "Community", FormMethod.Post, new { id = "invitationForm" }))
        {
            foreach (var f in Model)
            {
                if (!f.Accept)
                {
                    <div class="user" value=@f.InvitationID>
                        <div class="user-picture" style="background-image: url('@Url.Content("~/Images/" + f.Sender.ProfilePic)" )')"></div>
                        <div class="user-info">
                            <label class="user-info-name">@f.Sender.Nickname</label>
                            <label class="user-info-loc">@f.Sender.City</label>
                        </div>
                        <div class="add-friend-btn-container">
                            <div id="acc-inv" class="accept-inv-btn">Accept</div>
                            <div id="dec-inv" class="decline-inv-btn">Decline</div>
                        </div>
                    </div>
                }
            }
            <input type="hidden" name="invID" />
        }
    </div>
</div>

HomeLibrary/Views/Community/Messages.cshtml
@{
    ViewBag.Title = "Messages";
}

<h2>Messages</h2>

HomeLibrary/Views/Community/PicturesProfile.cshtml
@model List<HomeLibrary.Models.ProfilePicturesModels>

<div id="SinglePageContent" class="body-content-blank">
    <div class="library-view-content">
        <div id="right-panel" class="right-panel-section">
            <div class="library-navbar">
                <div class="library-navbar-header">
                    <p>Category</p>
                    <img id="close-navbar" src="~/Images/leave_btn.png" />
                </div>
                <ul class="library-navbar-list">
                    <li>
                        <img src="@Url.Content("~/Images/menu_arrow.png")" />
                        <a href="/Community/InformationManager">Change profile informations</a>
                    </li>
                    <li>
                        <img src="@Url.Content("~/Images/menu_arrow.png")" />
                        <a href="/Library/BorrowedBooks">Change account informations</a>
                    </li>
                    <li>
                        <img src="@Url.Content("~/Images/menu_arrow.png")" />
                        <a href="/Library/LendBooks">Block users</a>
                    </li>
                    <li>
                        <img src="@Url.Content("~/Images/menu_arrow.png")" />
                        <a href="/Community/PicturesProfile">Manage pictures</a>
                    </li>
                </ul>
            </div>
        </div>
        <div id="navbar-open" class="close-navbar-button">
            Open
        </div>
        <div id="left-panel" class="left-panel-section">
            <div class="left-panel-content">
                @using (Html.BeginForm("PicturesProfile", "Community", FormMethod.Post, new { id = "editProfile", enctype = "multipart/form-data" }))
                {
                    <div id="buttons-nav" class="add-profile-photo">
                        <div class="initial-btns">
                            <label id="remove-photo" class="remove-photo-btn">
                                Remove photo
                            </label>
                            <label id="add-photo" class="add-photo-btn">
                                <input type='file' name="file" id="add-photo-input" />
                                Add photo
                            </label>
                        </div>
                    </div>
                    <input type="hidden" name="choseToRemove">
                }
                @using (Html.BeginForm("PicturesSetter", "Community", FormMethod.Post, new { id = "photosetterform", enctype = "multipart/form-data" }))
                {
                    <div class="photo-setter-container">
                        <div id="photo-setter" class="photo-setter-class">
                            <div id="ph-chcbx" class="photo-btn">
                                <input type="checkbox" id="set-photo" value="pictures" />
                                <label>
                                    Set profile photo
                                </label>
                                <input type="hidden" name="choseBackground" />
                            </div>
                            <div id="bckg-chcbx" class="backgorund-btn">
                                <input type="checkbox" id="set-bckg" value="pictures" />
                                <label>
                                    Set background image
                                </label>
                                <input type="hidden" name="choseProfilePic" />
                            </div>
                        </div>
                    </div>
                }
                <div class="right-panel-manage">
                    <div class="right-panel-content-manage">
                        <div id="photos-id" class="photos">
                            @if (Model.Count > 0)
                            {
                                foreach (var p in Model)
                                {
                                    <div class="single-photo">
                                        <div class="photo-container">
                                            <div class="single-photo-img" id=@p.PictureID value=@p.PicturePath style="background-image: url('@Url.Content("~/Images/" + p.PicturePath)" )')" name="notclicked"></div>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                        <div class="error">
                            @Html.ValidationSummary(false, "", new { @class = "error" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HomeLibrary/Views/Community/UserProfile.cshtml
@model HomeLibrary.Models.BasicProfileInfoModels
<div id="profile-view" class="profile-view-content">
    @using (Html.BeginForm("Profile", "Community", FormMethod.Post, new { id = "Profile-form", enctype = "multipart/form-data" }))
    {

        <div id="profile-head" class="head-profile" style="background-image: url('@Url.Content("~/Images/" + Model.BackgroundPic)" )')" value=@Model.BackgroundPic>
            <div id="profile-mask" class="profile-head-mask"></div>
            <div id="profile-photo" class="photo-profile" style="background-image: url('@Url.Content("~/Images/" + Model.ProfilePic)" )')" value=@Model.ProfilePic>
            </div>
            <label class="nickname-profile">@Model.Nickname</label>
        </div>

    }
    <div class="head-profile-bottom">
        <ul class="profile-navbar">
            <li class="profile-navbar-li"><a href="/Community/PicturesProfile">Photos</a></li>
            <li class="profile-navbar-li"><a href="/Community/InformationManager">Informations</a></li>
            <li class="profile-navbar-li"><a href="/Community/Friends">Friends</a></li>
        </ul>
    </div>
    <div id="profile-body" class="corpse-profile">

    </div>
</div>